/**
 * Regenerates src/symbol-manifest.ts from the on-disk assets/symbols tree.
 *
 * The manifest maps a normalized mana-symbol key to its asset path so symbols
 * can be resolved without scanning the filesystem — which the browser build
 * cannot do. Run after adding/removing symbol SVGs:
 *
 *   npx tsx scripts/gen-symbol-manifest.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const root = path.resolve(__dirname, '..', 'assets', 'symbols');
const dirs = fs.readdirSync(root, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name);

const map: Record<string, string> = {};
for (const d of dirs) {
  for (const f of fs.readdirSync(path.join(root, d)).filter(f => f.endsWith('.svg'))) {
    map[f.slice(0, -4)] = `symbols/${d}/${f}`;
  }
}

const keys = Object.keys(map).sort();
let out = '// AUTO-GENERATED by scripts/gen-symbol-manifest.ts — do not edit by hand.\n';
out += '// Maps a normalized mana-symbol key (lowercase, slashes removed) to its asset path,\n';
out += '// relative to the package assets root. Enables symbol lookup without a filesystem scan\n';
out += '// (needed for the browser build).\n\n';
out += 'export const SYMBOL_MANIFEST: Record<string, string> = {\n';
for (const k of keys) out += `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},\n`;
out += '};\n\n';
out += '/** All symbol asset paths (relative to the assets root). */\n';
out += 'export const SYMBOL_PATHS: string[] = Object.values(SYMBOL_MANIFEST);\n';

fs.writeFileSync(path.resolve(__dirname, '..', 'src', 'symbol-manifest.ts'), out);
console.log(`wrote src/symbol-manifest.ts with ${keys.length} entries`);
