/**
 * Regenerates src/asset-manifest.ts from the on-disk assets tree.
 *
 * The renderer loads frame/pt/mask/crown images by computed paths, but coverage
 * varies per template (e.g. 'standard' has a pinline-textbox mask but no banner;
 * transform/pt have no colorless 'c' variant). Knowing which assets actually
 * exist lets the renderer request only those — avoiding 404s and enabling clean
 * fallbacks — and the browser build cannot scan the filesystem.
 *
 * Run after adding/removing frame/pt/mask/crown assets:
 *
 *   npx tsx scripts/gen-asset-manifest.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const root = path.resolve(__dirname, '..', 'assets');

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(full));
    else if (e.isFile() && e.name.endsWith('.webp')) out.push(path.relative(root, full));
  }
  return out;
}

// Subtrees the renderer probes by computed path (existence-tolerant).
const subtrees = ['frames', 'pt', 'masks', 'crowns'];
const files = subtrees
  .filter(d => fs.existsSync(path.join(root, d)))
  .flatMap(d => walk(path.join(root, d)))
  .map(p => p.split(path.sep).join('/'))
  .sort();

let out = '// AUTO-GENERATED by scripts/gen-asset-manifest.ts — do not edit by hand.\n';
out += '// The set of frame/pt/mask/crown asset paths that exist (relative to the assets\n';
out += '// root). Lets the renderer request only assets that exist (no 404s) and fall\n';
out += '// back cleanly; the browser build cannot scan the filesystem.\n\n';
out += 'export const ASSET_MANIFEST: ReadonlySet<string> = new Set([\n';
for (const f of files) out += `  ${JSON.stringify(f)},\n`;
out += ']);\n\n';
out += '/** Whether an asset exists, by path relative to the assets root. */\n';
out += 'export function assetExists(relativePath: string): boolean {\n';
out += '  return ASSET_MANIFEST.has(relativePath);\n';
out += '}\n';

fs.writeFileSync(path.resolve(__dirname, '..', 'src', 'asset-manifest.ts'), out);
console.log(`wrote src/asset-manifest.ts with ${files.length} entries`);
