/**
 * Writes src/version.ts from package.json's version so the browser build can
 * pin its default jsDelivr asset URL to the exact published version.
 * Runs as part of `npm run build`.
 */
import * as fs from 'fs';
import * as path from 'path';

const pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '..', 'package.json'), 'utf-8'));
const out = `// AUTO-GENERATED by scripts/gen-version.ts — do not edit by hand.\nexport const VERSION = ${JSON.stringify(pkg.version)};\n`;
fs.writeFileSync(path.resolve(__dirname, '..', 'src', 'version.ts'), out);
console.log(`wrote src/version.ts (VERSION = ${pkg.version})`);
