/**
 * Regenerates src/mask-manifest.ts from the on-disk assets/masks directory.
 *
 * Mask coverage varies per template (e.g. 'standard' has title/type/pinline/rules
 * but no pinline-textbox or banner; 'battle' and 'transformBack' have only
 * pinline-textbox). The renderer requests masks by a fixed region list, so it
 * needs to know which actually exist to avoid 404s — and the browser build can't
 * scan the filesystem. Run after adding/removing mask PNGs:
 *
 *   npx tsx scripts/gen-mask-manifest.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const root = path.resolve(__dirname, '..', 'assets', 'masks');
const files = fs
  .readdirSync(root, { withFileTypes: true })
  .filter(d => d.isFile() && d.name.endsWith('.png'))
  .map(d => `masks/${d.name}`)
  .sort();

let out = '// AUTO-GENERATED by scripts/gen-mask-manifest.ts — do not edit by hand.\n';
out += '// The set of frame-mask asset paths that exist (relative to the assets root).\n';
out += '// Used to request only masks a template actually has, avoiding 404s — and the\n';
out += '// browser build cannot scan the filesystem.\n\n';
out += 'export const MASK_MANIFEST: ReadonlySet<string> = new Set([\n';
for (const f of files) out += `  ${JSON.stringify(f)},\n`;
out += ']);\n';

fs.writeFileSync(path.resolve(__dirname, '..', 'src', 'mask-manifest.ts'), out);
console.log(`wrote src/mask-manifest.ts with ${files.length} entries`);
