// AUTO-GENERATED by scripts/gen-mask-manifest.ts — do not edit by hand.
// The set of frame-mask asset paths that exist (relative to the assets root).
// Used to request only masks a template actually has, avoiding 404s — and the
// browser build cannot scan the filesystem.

export const MASK_MANIFEST: ReadonlySet<string> = new Set([
  "masks/adventure-pinline.png",
  "masks/battle-pinline-textbox.png",
  "masks/class-pinline-textbox.png",
  "masks/fuse-bottom.png",
  "masks/fuse-top.png",
  "masks/modal-pinline-textbox.png",
  "masks/omen-main-pinline.png",
  "masks/omen-mask.png",
  "masks/omen-spell-pinline.png",
  "masks/planeswalker-pinline-textbox.png",
  "masks/planeswalker_tall-pinline-textbox.png",
  "masks/prepare-main-pinline.png",
  "masks/prepare-mask.png",
  "masks/prepare-spell-pinline.png",
  "masks/room-mask.png",
  "masks/saga-banner-right.png",
  "masks/saga-banner.png",
  "masks/saga-pinline-textbox.png",
  "masks/standard-frame.png",
  "masks/standard-pinline.png",
  "masks/standard-rules.png",
  "masks/standard-title.png",
  "masks/standard-type.png",
  "masks/transformBack-pinline-textbox.png",
  "masks/transformFront-pinline-textbox.png",
]);
